### ISSUE TITLE
Manual schedule - it is not possible to overried only selected rooms

### ISSUE THREAD

**Issue by havlejan** [qlerup/lovelace-thermostat-pro-timeline#43]
Hi @qlerup 

if I prepare a profile that contains a schedule for only some rooms, after activating the profile the default temperature is applied to the room for which the schedule is not defined, instead of these rooms not being overwritten and the standard schedule remaining activated.

I have already reported this issue (issue #9), at the end of it you can find the video).

**Comment by qlerup** [comment]
So you want the empty room in manual override to just follow the main schedule?

**Comment by qlerup** [comment]
hi @havlejan, 

I dont have time for in deep testing - but the next update should fix this.

**Comment by havlejan** [comment]
Hi @qlerup,

Unfortunately, after updating Thermostat Timeline Card to version 1.9.0, the issue is back.
When I activate the manual schedule, in all rooms where the manual schedule is not defined (schedule is empty), the default temperature is applied and overwrites the main schedule.

In version 1.8.0 everything worked.

**Comment by qlerup** [comment]
Hi @havlejan,

It this still a issue or can i close it?

**Comment by havlejan** [comment]
Hi @qlerup ,
I tested this problem once again. Finally, I found out that it still persists in version 1.9.
Last night, I focused on the visual side - in the graphical representation of schedules for individual rooms, nothing changes for rooms that do not have a defined manual schedule. That's why I thought everything is working.
But I did not check the status of individual climate sensors. Unfortunately, they switch to the default value regardless of the graphical representation of schedules.
In the attached screenshots, you can see how, after activating the manual schedule, the temperature in all climate sensors changes to the default temperature of the timeline card . Except for the room "Pokoj vychod", which is the only one for which I have a defined manual schedule.

Manual schedule inactive:

<img width="1630" height="741" alt="Image" src="https://github.com/user-attachments/assets/aa66f61e-2695-460d-9d31-528ddbd371fb" />

Manual schedule active:

<img width="1630" height="741" alt="Image" src="https://github.com/user-attachments/assets/f5c929fc-248c-4856-b92b-4b32dd7d3a42" />
